nginx:
  build: ./nginx/
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ${PROJECT_ROOT}/:/var/www/html/:rw
    - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
    - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./log/nginx/:/var/log/nginx/:rw
  links:
    - php-fpm:fpm
    - php54-fpm:fpm54

php-fpm:
  build: ./php/
  expose:
    - "9000"
  volumes:
    - ${PROJECT_ROOT}/:/var/www/html/:rw
    - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
    - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    - ./log/php-fpm/:/var/log/php-fpm/:rw

php54-fpm:
  build: ./php54/
  expose:
    - "9000"
  volumes:
    - ${PROJECT_ROOT}/:/var/www/html/:rw
    - ./conf/php54/php.ini:/usr/local/etc/php/php.ini:ro
    - ./conf/php54/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    - ./log/php54-fpm/:/var/log/php-fpm/:rw
  links:
    - mysql:mysql

cron:
  build: ./cron/
  volumes:
    - ${PROJECT_ROOT}/:/var/www/html/:rw
  links:
    - mysql:mysql

mysql:
  image: mysql:latest
  expose:
    - "3306"
  volumes:
    - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
    - ./mysql/:/var/lib/mysql/:rw
    - ./log/mysql/:/var/log/mysql/:rw
  environment:
    MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
      - 8080:80
  links:
    - mysql:mysql
  environment:
      PMA_HOST: mysql